CREATE DATABASE  IF NOT EXISTS router;
USE router;

CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	full_name VARCHAR(255)  NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	role ENUM('ADMIN','APPRENANT') NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


